#!/usr/bin/env bash
# Generate STAR's six harness skill trees from the authored copy in .agents/skills.
#
#   bash .github/scripts/port.sh              # check: every tree still matches what
#                                             # .agents plus the rules would produce
#   bash .github/scripts/port.sh --write      # write the generated bodies into the trees
#   bash .github/scripts/port.sh --regen      # re-record the overrides from the trees
#   bash .github/scripts/port.sh --tree pi …  # one tree (repeatable), any mode
#
# The neutral source and six trees ship the same skills to six agent harnesses, and each
# harness names its own terminal, file reader, question tool and sub-agent. That
# made every wording change a seven-times edit that nothing checked: a sentence
# reworded in six trees and missed in the seventh drew no error, because no file
# ever claimed to be a copy of another. This says so, and proves it.
#
# Two adaptation inputs per harness, in .github/scripts/port/:
#   <tree>.rules      ordered `pattern<TAB>replacement`, that harness's vocabulary
#   <tree>.overrides  every span the vocabulary cannot reach — i.e. every place the
#                     tree genuinely says something else, anchored by generated
#                     source lines
#
# The authored neutral wording is stored once under .agents/skills. A generated
# file whose complete bytes match that source is a relative link; harness-specific
# wording is a real file. No manifest records which case applies: every run derives
# it from the generated bytes.
#
# Claude is now an adapter, not the baseline. Existing non-Claude rules still map
# Claude vocabulary to their harness, so generation first applies claude.rules and
# claude.overrides to the neutral source, then applies the selected harness rules
# and overrides. This preserves the established harness-specific wording without
# making .claude/skills an authored intermediate tree.
# Downstream projects never see the links: execs/update.sh writes out what one
# points at, so an installed tree is real files, self-contained, exactly as
# before.
#
# Frontmatter is not generated. Each harness tunes its own `description` to its own
# length limit and trigger wording; check_consistency.sh holds those invariants.
# Everything below the closing `---` is generated.
#
# --regen accepts the selected trees as they stand and rewrites their override files.
# It is the deliberate move after porting a passage by hand — never the way to make
# a red check go green, which is what makes a failing --check meaningful.
set -uo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd -P)"
MODE="check"
TREES=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check) MODE="check"; shift ;;
        --write) MODE="write"; shift ;;
        --regen) MODE="regen"; shift ;;
        --tree)  TREES+=("${2#.}"); shift 2 ;;
        # the whole header block, however long it grows — a line range would go
        # stale the next time something is explained here
        -h|--help) awk 'NR > 1 && /^#/ { sub(/^# ?/, ""); print; next } NR > 1 { exit }' \
                       "${BASH_SOURCE[0]}"; exit 0 ;;
        *) echo "port.sh: unknown argument '$1'" >&2; exit 2 ;;
    esac
done
[[ ${#TREES[@]} -gt 0 ]] || TREES=(claude cursor dsh kimi-code pi qwen)

command -v perl >/dev/null 2>&1 || { echo "port.sh: perl not found" >&2; exit 2; }

echo "port: ${MODE} — .agents/skills -> ${#TREES[@]} harness tree(s)"
PORT_ROOT="${ROOT_DIR}" perl "${ROOT_DIR}/.github/scripts/port/port.pl" "${MODE}" "${TREES[@]}"
rc=$?

if [[ "${MODE}" == "check" ]]; then
    if [[ ${rc} -eq 0 ]]; then
        echo "ok  every harness tree is what .agents/skills plus its adapters produces,"
        echo "    and byte-identical files link back to the authored source"
    else
        cat <<'MSG'

A tree no longer matches. Either the tree was edited directly — port the semantic
change to .agents/skills and re-run --write — or a generated source line used by
an override was reworded. In the latter case, port the same change into that
harness's override and then run --regen for that tree.

A file reported as one that must be a link, or as a link that is no longer shared,
needs neither: the wording moved it across the line and --write puts it on the
right side.
MSG
    fi
fi
exit ${rc}
